### ISSUE TITLE
Idle-server daemon causing unusable termux session

### ISSUE THREAD

**Issue by jacobeva** [Edenhofer/abs#13]
When running papermc with the idle-server daemon enabled in the config file and starting it via `papermc start`, the following error occurs if the user does not have a tmux session open for papermc (started by `papermc console`):
`java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.hasPermission(String)" because the return value of "net.minecraft.commands.CommandListenerWrapper.getBukkitSender()" is null       
        at net.minecraft.commands.CommandDispatcher.lambda$new$0(CommandDispatcher.java:210) ~[patched_1.17.1.jar:git-Paper-243]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.17.1.jar:git-Paper-243]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:358) ~[patched_1.17.1.jar:git-Paper-243]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:348) ~[patched_1.17.1.jar:git-Paper-243]
        at io.papermc.paper.console.BrigadierCommandHighlighter.highlight(BrigadierCommandHighlighter.java:28) ~[patched_1.17.1.jar:git-Paper-243]
        at org.jline.reader.impl.LineReaderImpl.getHighlightedBuffer(LineReaderImpl.java:3818) ~[patched_1.17.1.jar:git-Paper-243]
        at org.jline.reader.impl.LineReaderImpl.getDisplayedBufferWithPrompts(LineReaderImpl.java:3800) ~[patched_1.17.1.jar:git-Paper-243]
        at org.jline.reader.impl.LineReaderImpl.redisplay(LineReaderImpl.java:3700) ~[patched_1.17.1.jar:git-Paper-243]
        at org.jline.reader.impl.LineReaderImpl.doCleanup(LineReaderImpl.java:2427) ~[patched_1.17.1.jar:git-Paper-243]
        at org.jline.reader.impl.LineReaderImpl.cleanup(LineReaderImpl.java:2419) ~[patched_1.17.1.jar:git-Paper-243]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:648) ~[patched_1.17.1.jar:git-Paper-243]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[patched_1.17.1.jar:git-Paper-243]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[patched_1.17.1.jar:git-Paper-243]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[patched_1.17.1.jar:git-Paper-243]
        at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:113) ~[patched_1.17.1.jar:git-Paper-243]`
This seems to be due to the idle-server daemon issuing list commands before the server is ready to accept input, which prevents any further input later on.

**Comment by Edenhofer** [comment]
Thank you for the bug report. It is unfortunate that it is necessary to work around this. Ideally papermc would not just bail if it receives input "too early" but instead it should gracefully handle the input as soon as it can.

I took a look at the code and to me it seems like the best option would be to just wait for some initial time in `idle_server_daemon`. To get an idea of how long it takes the server to start in your case, it would be nice if you could share some time measurements. If you can, please stop the time from issuing the initial `papermc start` up to papermc being able to handle input, i.e. a prompt showing up.

The setting of `CHECK_PLAYER_TIME` in `/etc/conf.d/papermc` would also be interesting to know. I imagine it is rather low (<10 s or even <5 s).

**Comment by jacobeva** [comment]
Startup of the server takes about 45 seconds for me and my `CHECK_PLAYER_TIME` is set to 30s, so it's easy to see where the issue is coming from.

**Comment by jacobeva** [comment]
Would it not be possible to simply monitor the tmux stdout for the `Done!` message, that'd be a much better implementation than just having a timer no?

**Comment by Edenhofer** [comment]
I see. It is a bit surprising to me that papermc isn't able to handle input at that stage.

In principle yes, however different flavors of the Minecraft server tend to use different syntax keywords to communicate a successful init. Since the script is agnostic to the choice of server flavor, I would like to avoid hard-coding any specific messages.

**Comment by jacobeva** [comment]
Ah I see. Well the issue is world load times will be different from server to server right? Not sure a timer would be a 100% fullproof implementation. Still, it's better than nothing though.

**Comment by Edenhofer** [comment]
I have been pondering a lot about this and I can't come up with a generic catch-all waiting scheme. I am even thinking whether it would actually be better to raise this issue with the papermc folks. In my opinion, papermc should gracefully handle such cases and it would be best to fix this upstream. @elimin-8 Would you kindly raise an issue with papermc?

In case they really think the server should fail upon receiving early input, I might introduce a hacky waiting period although I certainly don't like the idea.

**Comment by jacobeva** [comment]
Opened. I'll keep you updated.

**Comment by Edenhofer** [comment]
@elimin-8 While working on yielding error message for a failure during server startup, I addressed this issue partly. Namely, the server now checks for `done` being printed during startup. However, regardless of the message, it will skip waiting after 15 seconds as to not block indefinitely. WDYT about this approach?

P.S. it is nice to see that the papermc folks have resolved the root cause of the problem completely.
